# Top-level configuration (Defaults, potentially used by wrangler dev)
name = "druckshirt-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
upload_source_maps = true

# Explicit build step
[build]
command = "npm install"
# Remove rollup options externalizing toucan-js as it's removed
# [build.rollup_options]
# external = ["toucan-js"]

# --- Top-Level Bindings & Vars ---
# These settings are used by default for `wrangler dev` if no --env flag is specified.
# It's recommended to use specific local resource names/IDs here if you have them,
# or run `wrangler dev --env staging` to use your staging configuration locally.
# The current KV ID looks like a Cloudflare ID, ensure this is intended for local dev.
[[kv_namespaces]]
binding = "STATE_KV"
id = "b5d117a32d2a4d2c880cc5537acfdbc9" # Default/Local ID (Verify if correct for local)

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "druckmeinshirt-images-local" # Default/Local Name

[[queues.producers]]
queue = "druckshirt-token-fulfillment" # Default/local queue name
binding = "TOKEN_QUEUE"

[[queues.producers]]
queue = "druckshirt-order-fulfillment" # Default/local queue name
binding = "ORDER_QUEUE"

[vars]
# FIXME: Replace placeholders below with appropriate values for LOCAL development or remove if unused.
ALLOWED_ORIGINS = "http://localhost:3000,<YOUR_PRODUCTION_FRONTEND_URL_HERE>" # Example: Localhost + Prod URL
R2_PUBLIC_URL_PREFIX = "<YOUR_LOCAL_OR_STAGING_R2_PUBLIC_URL_HERE>" # Example: Use staging R2 for local dev

# --- Environment: Staging ---
[env.staging]
name = "druckshirt-api-gateway-staging"

[env.staging.vars]
# ALLOWED_ORIGINS is correctly set for staging frontend + localhost
ALLOWED_ORIGINS = "http://localhost:3000,https://druckshirt-frontend.pages.dev"
# FIXME: You MUST replace this placeholder with your actual staging R2 public URL prefix!
# Example: "https://pub-xxxxxxxx.r2.dev" or your custom domain pointing to the staging R2 bucket.
R2_PUBLIC_URL_PREFIX = "<YOUR_STAGING_R2_PUBLIC_URL_HERE>" # Replace this

# Staging bindings use specific staging resources
[[env.staging.kv_namespaces]]
binding = "STATE_KV"
id = "0cc66f93317c4798af20561bb8c4aa23" # Verified Staging ID

[[env.staging.r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "druckmeinshirt-images-staging" # Verified Staging Name

[[env.staging.queues.producers]]
queue = "druckshirt-token-fulfillment-staging" # Verified Staging Queue
binding = "TOKEN_QUEUE"

[[env.staging.queues.producers]]
queue = "druckshirt-order-fulfillment-staging" # Verified Staging Queue
binding = "ORDER_QUEUE"

# Secrets for staging are set via Cloudflare Dashboard or `wrangler secret put <SECRET_NAME> --env staging`

# --- Environment: Production ---
[env.production]
name = "druckshirt-api-gateway-production"

# Production Bindings (Consistent format)
[[env.production.kv_namespaces]]
binding = "STATE_KV"
id = "59d2638e44714737923ac9c12452209b" # Verified Production ID

[[env.production.r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "druckmeinshirt-images-production" # Verified Production Name

[[env.production.queues.producers]]
queue = "token-fulfillment-queue-production" # Verified Production Queue
binding = "TOKEN_QUEUE"

[[env.production.queues.producers]]
queue = "order-fulfillment-queue-production" # Verified Production Queue
binding = "ORDER_QUEUE"

[env.production.vars]
# FIXME: You MUST replace this placeholder with your actual PRODUCTION frontend URL!
ALLOWED_ORIGINS = "<YOUR_PRODUCTION_FRONTEND_URL_HERE>" # Replace <...>
# FIXME: You MUST replace this placeholder with your actual PRODUCTION R2 public URL prefix!
# Example: "https://pub-yyyyyyyy.r2.dev" or your custom domain pointing to the production R2 bucket.
R2_PUBLIC_URL_PREFIX = "<YOUR_PRODUCTION_R2_PUBLIC_URL_HERE>" # Replace <...>

# Secrets for production are set via Cloudflare Dashboard or `wrangler secret put <SECRET_NAME> --env production`
# Or via GitHub Actions secrets during deployment.
# DO NOT add secrets directly to this file.

# --- REMOVED Redundant/Confusing Sections Below --- 