# Top-level configuration (Defaults, potentially used by wrangler dev)
name = "druckshirt-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Bindings (Defaults/Local Dev)
[[kv_namespaces]]
binding = "STATE_KV"
id = "b5d117a32d2a4d2c880cc5537acfdbc9" # Updated: Local ID

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "druckmeinshirt-images-local" # Updated: Local Name

[[queues.producers]]
queue = "druckshirt-token-fulfillment" # Default/local queue name
binding = "TOKEN_QUEUE"

[[queues.producers]]
queue = "druckshirt-order-fulfillment" # Default/local queue name
binding = "ORDER_QUEUE"

# Environment: Staging
[env.staging]
name = "druckshirt-api-gateway-staging"

# Define vars explicitly for staging
[env.staging.vars]
# Set allowed origins for staging frontend, previews, and localhost
ALLOWED_ORIGINS = "https://druckshirt-frontend.pages.dev,*.druckshirt-frontend.pages.dev,http://localhost:5173"
# FIXME: You MUST replace this placeholder with your actual staging R2 public URL prefix!
# Example: "https://pub-xxxxxxxx.r2.dev" or your custom domain pointing to the staging R2 bucket.
R2_PUBLIC_URL_PREFIX = "https://pub-ce3cfb8f641747a4b56c9c9f3bbd7096.r2.dev" # Replace this

# Define bindings explicitly for staging (use specific staging resources)
[[env.staging.kv_namespaces]]
binding = "STATE_KV"
id = "0cc66f93317c4798af20561bb8c4aa23" # Updated: Staging ID

[[env.staging.r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "druckmeinshirt-images-staging" # Updated: Staging Name

[[env.staging.queues.producers]]
queue = "druckshirt-token-fulfillment-staging" # Staging queue name
binding = "TOKEN_QUEUE"

[[env.staging.queues.producers]]
queue = "druckshirt-order-fulfillment-staging" # Staging queue name
binding = "ORDER_QUEUE"

# Secrets for staging would be set via:
# `wrangler secret put <SECRET_NAME> --env staging`

# Environment: Production
[env.production]
name = "druckshirt-api-gateway-production"

# --- Production Values ---
kv_namespaces = [
  { binding = "STATE_KV", id = "59d2638e44714737923ac9c12452209b" } # Verified Production ID
]
r2_buckets = [
  { binding = "IMAGE_BUCKET", bucket_name = "druckmeinshirt-images-production" } # Verified Production Name
]
[[env.production.queues.producers]]
queue = "token-fulfillment-queue-production" # Verified Production Queue
binding = "TOKEN_QUEUE"
[[env.production.queues.producers]]
queue = "order-fulfillment-queue-production" # Verified Production Queue
binding = "ORDER_QUEUE"

# Add production vars section
[env.production.vars]
ALLOWED_ORIGINS = "https://druckshirt-frontend.pages.dev,*.druckshirt-frontend.pages.dev,http://localhost:5173"
# Ensure you have a production R2_PUBLIC_URL_PREFIX set via secrets or here
# R2_PUBLIC_URL_PREFIX = "<YOUR_PRODUCTION_R2_PUBLIC_URL_HERE>" # Example

# --- End Production Values ---

# Variables (Top-Level - Consider if these should match production or local)
# Usually overridden by environment, but sets default for `wrangler dev` if no --env specified
[vars]
# Set allowed origins for production, previews, and localhost
ALLOWED_ORIGINS = "https://druckshirt-frontend.pages.dev,*.druckshirt-frontend.pages.dev,http://localhost:5173"
R2_PUBLIC_URL_PREFIX = "https://pub-ce3cfb8f641747a4b56c9c9f3bbd7096.r2.dev" # Replace this if default differs

# DO NOT add secrets directly to this file.

# Example Secret Placeholders (Set via wrangler secret put or GitHub Actions)
# [vars] # Uncomment if setting defaults here, usually secrets are env-specific
# STRIPE_SECRET_KEY = "placeholder"
# STRIPE_WEBHOOK_SECRET = "placeholder"
# PRINTFUL_API_KEY = "placeholder"
# PRINTFUL_STORE_ID = "placeholder"
# RESEND_API_KEY = "placeholder"
# XAI_API_KEY = "placeholder"
# PRINTIFY_API_KEY = "placeholder"
# PRINTIFY_SHOP_ID = "placeholder"

# Variables
# [vars]
# ALLOWED_ORIGINS = "http://localhost:3000,<YOUR_PRODUCTION_FRONTEND_URL_HERE>"
# R2_PUBLIC_URL_PREFIX = "https://pub-ce3cfb8f641747a4b56c9c9f3bbd7096.r2.dev"

# Secrets are set via GitHub Actions during deploy
# [vars]
# STRIPE_SECRET_KEY = "placeholder"
# STRIPE_WEBHOOK_SECRET = "placeholder"
# PRINTFUL_API_KEY = "placeholder"
# RESEND_API_KEY = "placeholder"
# XAI_API_KEY = "placeholder" 