# Top-level configuration
name = "druckshirt-queue-consumer"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Bindings
[[kv_namespaces]]
binding = "STATE_KV"
id = "<YOUR_KV_NAMESPACE_ID>" # Replace with your actual KV namespace ID (should match api-gateway's)
# preview_id = "<YOUR_PREVIEW_KV_NAMESPACE_ID>" # Optional: for local dev/preview

[[queues.consumers]]
queue = "druckshirt-token-fulfillment"
# max_batch_size = 10 # Optional: Default is 100
# max_batch_timeout = 5 # Optional: Default is 30 seconds
# max_retries = 3 # Optional: Default is 3
# dead_letter_queue = "druckshirt-dlq" # Optional: Define a DLQ

[[queues.consumers]]
queue = "druckshirt-order-fulfillment"
# max_retries = 5 # Example: Allow more retries for orders
# dead_letter_queue = "druckshirt-dlq" # Optional: Define a DLQ

# Environment: Staging
[env.staging]
name = "druckshirt-queue-consumer-staging"
# [[env.staging.kv_namespaces]]
# binding = "STATE_KV"
# id = "<YOUR_STAGING_KV_ID>"
# [[env.staging.queues.consumers]]
# queue = "druckshirt-token-fulfillment-staging"
# [[env.staging.queues.consumers]]
# queue = "druckshirt-order-fulfillment-staging"

# Secrets for staging would be set via:
# `wrangler secret put <SECRET_NAME> --env staging`

# Environment: Production
# [env.production]
# name = "druckshirt-queue-consumer-production" # Optional
# ... other production-specific bindings/configs ...

# Secrets are set via GitHub Actions during deploy
# [vars]
# STRIPE_SECRET_KEY = "placeholder"
# PRINTFUL_API_KEY = "placeholder"
# RESEND_API_KEY = "placeholder" 