# Top-level configuration
name = "druckmeinshirt-queue-consumer"
main = "src/index.ts"
compatibility_date = "2024-05-15"

# Bindings
kv_namespaces = [
  { binding = "STATE_KV", id = "0cc66f93317c4798af20561bb8c4aa23", preview_id = "0cc66f93317c4798af20561bb8c4aa23" } # Using Staging ID for preview
]

[[queues.consumers]]
queue = "token-fulfillment-queue-staging"
max_batch_size = 1 # Process one message at a time for simplicity
max_retries = 3

[[queues.consumers]]
queue = "order-fulfillment-queue-staging"
max_batch_size = 1 # Process one message at a time
max_retries = 3

# Environment: Staging
[env.staging]
name = "druckmeinshirt-queue-consumer-staging"
kv_namespaces = [
  { binding = "STATE_KV", id = "0cc66f93317c4798af20561bb8c4aa23" }
]
[[env.staging.queues.consumers]]
queue = "token-fulfillment-queue-staging"
max_batch_size = 1
max_retries = 3
[[env.staging.queues.consumers]]
queue = "order-fulfillment-queue-staging"
max_batch_size = 1
max_retries = 3

# Environment: Production
[env.production]
name = "druckmeinshirt-queue-consumer-production"
kv_namespaces = [
  { binding = "STATE_KV", id = "59d2638e44714737923ac9c12452209b" }
]
[[env.production.queues.consumers]]
queue = "token-fulfillment-queue-production"
max_batch_size = 1
max_retries = 3
[[env.production.queues.consumers]]
queue = "order-fulfillment-queue-production"
max_batch_size = 1
max_retries = 3

# Secrets are set via GitHub Actions during deploy
# [vars]
# STRIPE_SECRET_KEY = "placeholder"
# PRINTFUL_API_KEY = "placeholder"
# RESEND_API_KEY = "placeholder" 