name: CI Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    name: Run Tests, Linter, Formatter, Type Check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            workers/api-gateway/package-lock.json
            workers/queue-consumer/package-lock.json

      - name: Install All Dependencies
        run: |
          npm ci --prefix frontend
          npm ci --prefix workers/api-gateway
          npm ci --prefix workers/queue-consumer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # If using private packages

      - name: Build Frontend
        run: npm run build --prefix frontend

      - name: Run API Gateway Tests
        run: npm test --prefix workers/api-gateway -- --run --passWithNoTests

      - name: Run Queue Consumer Tests
        run: npm test --prefix workers/queue-consumer -- --run --passWithNoTests

      - name: Typecheck API Gateway
        run: npm run typecheck --prefix workers/api-gateway

      - name: Typecheck Queue Consumer
        run: npm run typecheck --prefix workers/queue-consumer

  security:
    runs-on: ubuntu-latest
    name: Security Checks
    # Add permissions for CodeQL to write security events and allow repo checkout
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript # Covers JS and TS

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
        # No 'with' needed here usually if specified in init

  documentation:
    runs-on: ubuntu-latest
    name: Documentation Checks (Informational)
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder - Comment Check
        run: |
          echo "TODO: Add basic comment presence check (non-blocking)"
        continue-on-error: true
