name: CI Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    name: Run Tests, Linter, Formatter, Type Check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            workers/**/package-lock.json

      - name: Install All Dependencies
        run: |
          npm ci --prefix frontend
          npm ci --prefix workers/api-gateway
          npm ci --prefix workers/queue-consumer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # If using private packages

      - name: Placeholder - Run Checks
        run: #echo "TODO: Add lint, format, typecheck, unit test steps here"

  security:
    runs-on: ubuntu-latest
    name: Security Checks
    steps:
      - uses: actions/checkout@v4

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
        # with:
        #   languages: "javascript" # Adjust if using TypeScript primarily

  documentation:
    runs-on: ubuntu-latest
    name: Documentation Checks (Informational)
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder - Comment Check
        run: #echo "TODO: Add basic comment presence check (non-blocking)"
        continue-on-error: true
