name: Deploy Backend Workers

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Workers
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            workers/api-gateway/package-lock.json
            workers/queue-consumer/package-lock.json

      - name: Install Dependencies & Setup Wrangler
        run: |
          npm install -g wrangler
          npm ci --prefix workers/api-gateway
          npm ci --prefix workers/queue-consumer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # If using private packages

      - name: Determine Environment
        id: get_env
        run: echo "CLOUDFLARE_ENV=${{ github.ref_name == 'main' && 'production' || 'staging' }}" >> $GITHUB_ENV

      - name: Deploy API Gateway Worker
        id: deploy_api_gateway
        run: wrangler deploy --env $CLOUDFLARE_ENV
        working-directory: ./workers/api-gateway
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Pass secrets required by the worker
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          # Add Sentry DSN and other Sentry-related secrets if needed
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_HOST_URL: ${{ secrets.POSTHOG_HOST_URL }}

      - name: Upload API Gateway Source Maps to Sentry
        if: steps.deploy_api_gateway.outcome == 'success' && env.CLOUDFLARE_ENV != 'local' && env.SENTRY_AUTH_TOKEN != ''
        working-directory: ./workers/api-gateway
        run: |
          npm install --no-save @sentry/cli@latest
          export SENTRY_ORG=high-five-financial-education
          export SENTRY_PROJECT=YOUR_API_GATEWAY_PROJECT_SLUG # <-- REPLACE
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          echo "Creating Sentry release: $SENTRY_RELEASE"
          sentry-cli releases new "$SENTRY_RELEASE"
          sentry-cli releases set-commits "$SENTRY_RELEASE" --auto
          echo "Uploading API Gateway source maps..."
          # Adjust include path if necessary based on wrangler output
          sentry-cli releases files "$SENTRY_RELEASE" upload-sourcemaps --url-prefix '~/' --validate ./dist
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: debug

      - name: Deploy Queue Consumer Worker
        id: deploy_queue_consumer
        run: wrangler deploy --env $CLOUDFLARE_ENV
        working-directory: ./workers/queue-consumer
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Pass secrets required by the worker
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          # Add Sentry DSN and other Sentry-related secrets if needed
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_HOST_URL: ${{ secrets.POSTHOG_HOST_URL }}

      - name: Upload Queue Consumer Source Maps to Sentry
        if: steps.deploy_queue_consumer.outcome == 'success' && env.CLOUDFLARE_ENV != 'local' && env.SENTRY_AUTH_TOKEN != ''
        working-directory: ./workers/queue-consumer
        run: |
          npm install --no-save @sentry/cli@latest
          export SENTRY_ORG=high-five-financial-education
          export SENTRY_PROJECT=YOUR_QUEUE_CONSUMER_PROJECT_SLUG # <-- REPLACE
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          echo "Uploading Queue Consumer source maps for release: $SENTRY_RELEASE"
          sentry-cli releases files "$SENTRY_RELEASE" upload-sourcemaps --url-prefix '~/' --validate ./dist
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: debug

      - name: Finalize Sentry Release
        if: (steps.deploy_api_gateway.outcome == 'success' || steps.deploy_queue_consumer.outcome == 'success') && env.CLOUDFLARE_ENV != 'local' && env.SENTRY_AUTH_TOKEN != ''
        run: |
          npm install --no-save @sentry/cli@latest
          export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          echo "Finalizing Sentry release: $SENTRY_RELEASE"
          sentry-cli releases finalize "$SENTRY_RELEASE"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_LOG_LEVEL: debug
